import type { Metadata } from "next";
import { Rasa, Inter, JetBrains_Mono } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer"; // <--- Import Footer
import "./globals.css";

// 1. Primary Font (Serif)
const rasa = Rasa({ 
  subsets: ["latin"], 
  variable: "--font-rasa",
  weight: ["300", "400", "500", "600", "700"] 
});

// 2. Secondary Font (UI)
const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-inter" 
});

// 3. Code Font
const jetbrains = JetBrains_Mono({ 
  subsets: ["latin"], 
  variable: "--font-jetbrains" 
});

export const metadata: Metadata = {
  title: "Bolt.ai Titanium Clone",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rasa.variable} ${inter.variable} ${jetbrains.variable} font-sans bg-titanium-950 text-titanium-100 overflow-x-hidden flex flex-col min-h-screen`}>
        
        {/* 1. Navbar (Fixed at top) */}
        <Navbar />
        
        {/* 2. Main Content (Pushes footer down) */}
        <main className="flex-1 pt-16 relative"> 
            {children}
        </main>

        {/* 3. Footer (Stays at bottom) */}
        <Footer />
        
      </body>
    </html>
  );
}