import type { Metadata } from "next";
import { Rasa, Inter, JetBrains_Mono } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import "./globals.css";
import { Provider } from "jotai";

const rasa = Rasa({
  subsets: ["latin"],
  variable: "--font-rasa",
  weight: ["300", "400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Docent AI",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rasa.variable} ${inter.variable} ${jetbrains.variable} font-sans antialiased text-titanium-100 flex flex-col h-screen overflow-hidden bg-gradient-to-br from-[#0f172a] via-[#020617] to-black`}
      >
        <div className="fixed inset-0 -z-50 pointer-events-none">
          <div className="absolute top-[-20%] left-1/2 -translate-x-1/2 w-[80%] h-[60vh] bg-blue-600/10 blur-[120px] rounded-full mix-blend-screen"></div>
        </div>

        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
